version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/gamingDB
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RAWG_API_KEY=${RAWG_API_KEY}
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
